version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    #ports:
      # These ports are in format <host-port>:<container-port>
    #  - '80:80' # Public HTTP Port
    #  - '443:443' # Public HTTPS Port
    #  - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      proxy-network:
        ipv4_address: $IPV4_ADDRESS
    # Uncomment the next line if you uncomment anything in the section
    env_file: stack.env
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

volumes:
  data:
  letsencrypt:
networks:
  proxy-network:
    external: true
    


